[36m[2022-06-17 21:08:01 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:08:01 DEBUG] [cli:113][39m Running command 'init'
[36m[2022-06-17 21:08:01 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:08:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:12:46 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:12:46 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:12:46 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:12:47 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:12:47 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:12:47 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:12:47 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:12:47 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-06-17 21:12:47 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 21:12:47 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:12:47 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:12:47 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 21:12:47 DEBUG] [caching:42][39m Clearing activities cache
[31m[2022-06-17 21:12:47 ERROR] [cli:260][39m an activity must have a type
[36m[2022-06-17 21:12:47 DEBUG] [cli:261][39m an activity must have a type
[36m[2022-06-17 21:13:11 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:13:11 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:13:11 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:13:11 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:13:11 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:13:11 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:13:11 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:13:11 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-06-17 21:13:11 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 21:13:11 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:13:11 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:13:11 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 21:13:11 DEBUG] [caching:42][39m Clearing activities cache
[31m[2022-06-17 21:13:11 ERROR] [cli:260][39m an activity must have a type
[36m[2022-06-17 21:13:11 DEBUG] [cli:261][39m an activity must have a type
[36m[2022-06-17 21:13:45 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:13:45 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:13:45 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:13:45 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:13:45 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:13:45 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:13:45 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:13:45 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-06-17 21:13:45 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 21:13:45 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:13:45 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:13:45 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 21:13:45 DEBUG] [caching:42][39m Clearing activities cache
[31m[2022-06-17 21:13:45 ERROR] [cli:260][39m an activity must have a type
[36m[2022-06-17 21:13:45 DEBUG] [cli:261][39m an activity must have a type
[36m[2022-06-17 21:16:34 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:16:34 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:16:34 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:16:35 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:16:35 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:16:35 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:16:35 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:16:35 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-06-17 21:16:35 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 21:16:35 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:16:35 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:16:35 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 21:16:35 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 21:16:35 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:16:35 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:16:35 DEBUG] [caching:35][39m Cached 1 activities
[36m[2022-06-17 21:16:35 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:16:35 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:16:35 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 21:16:35 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 21:16:35 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 21:16:35 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 21:16:35 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 21:16:35 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 21:16:35 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 21:16:35 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 21:16:35 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 21:16:35 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 21:16:35 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 21:16:35 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 21:16:35 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 21:16:35 DEBUG] [__init__:75][39m Using AWS region 'us-east-1'
[36m[2022-06-17 21:16:35 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 21:16:35 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-0844f33bdf9c15e5c']})' from AZ 'None' to be stopped
[36m[2022-06-17 21:16:35 DEBUG] [actions:587][39m Stopping instances: ['i-0844f33bdf9c15e5c']
[36m[2022-06-17 21:16:36 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-0844f33bdf9c15e5c', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '45f6b0f4-5581-4e14-ba0e-f92fb1ce971d', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '45f6b0f4-5581-4e14-ba0e-f92fb1ce971d', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 01:16:42 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[36m[2022-06-17 21:16:36 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 21:16:36 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 21:16:36 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 21:16:36 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 21:16:36 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 21:16:36 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 21:16:36 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 21:16:36 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 21:16:36 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 21:16:36 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:23:08 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:23:08 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:23:08 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:23:08 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:23:08 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:23:08 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:23:08 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:23:08 DEBUG] [caching:35][39m Cached 2 activities
[32m[2022-06-17 21:23:08 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 21:23:08 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:23:08 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:23:08 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 21:23:08 DEBUG] [caching:42][39m Clearing activities cache
[31m[2022-06-17 21:23:08 ERROR] [cli:260][39m argument 'instance_id' is not part of the function signature in activity 'start_instances'
[36m[2022-06-17 21:23:08 DEBUG] [cli:261][39m argument 'instance_id' is not part of the function signature in activity 'start_instances'
[36m[2022-06-17 21:23:33 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:23:33 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:23:33 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:23:33 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:23:33 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:23:33 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:23:33 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:23:33 DEBUG] [caching:35][39m Cached 2 activities
[32m[2022-06-17 21:23:33 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 21:23:33 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:23:33 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:23:33 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 21:23:33 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 21:23:33 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:23:33 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:23:33 DEBUG] [caching:35][39m Cached 2 activities
[36m[2022-06-17 21:23:33 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:23:33 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:23:33 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 21:23:33 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 21:23:33 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 21:23:33 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 21:23:33 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 21:23:33 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 21:23:33 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 21:23:33 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 21:23:33 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 21:23:33 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 21:23:33 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 21:23:33 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 21:23:33 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 21:23:33 DEBUG] [__init__:75][39m Using AWS region 'us-east-1'
[36m[2022-06-17 21:23:33 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 21:23:34 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-0844f33bdf9c15e5c']})' from AZ 'None' to be stopped
[36m[2022-06-17 21:23:34 DEBUG] [actions:587][39m Stopping instances: ['i-0844f33bdf9c15e5c']
[36m[2022-06-17 21:23:34 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 80, 'Name': 'stopped'}, 'InstanceId': 'i-0844f33bdf9c15e5c', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}], 'ResponseMetadata': {'RequestId': '55957daf-e8b7-4428-bd06-7f15b0ce2cca', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '55957daf-e8b7-4428-bd06-7f15b0ce2cca', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '578', 'date': 'Sat, 18 Jun 2022 01:23:40 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 21:23:34 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 21:23:44 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 21:23:44 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 21:23:44 INFO] [activity:204][39m Action: start-an-ec2-instance
[36m[2022-06-17 21:23:44 DEBUG] [python:33][39m Activity 'start-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 21:23:44 DEBUG] [__init__:75][39m Using AWS region 'us-east-1'
[36m[2022-06-17 21:23:44 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 21:23:44 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 284, in start_instances
        instance_types = get_instance_type_by_id(instance_ids, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 573, in get_instance_type_by_id
        res = client.describe_instances(InstanceIds=instance_ids)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 874, in _make_api_call
        request_dict = self._convert_to_request_dict(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 935, in _convert_to_request_dict
        request_dict = self._serializer.serialize_to_request(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/validate.py", line 381, in serialize_to_request
        raise ParamValidationError(report=report.generate_report())
    botocore.exceptions.ParamValidationError: Parameter validation failed:
    Invalid type for parameter InstanceIds, value: i-0844f33bdf9c15e5c, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 284, in start_instances
        instance_types = get_instance_type_by_id(instance_ids, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 573, in get_instance_type_by_id
        res = client.describe_instances(InstanceIds=instance_ids)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 874, in _make_api_call
        request_dict = self._convert_to_request_dict(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 935, in _convert_to_request_dict
        request_dict = self._serializer.serialize_to_request(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/validate.py", line 381, in serialize_to_request
        raise ParamValidationError(report=report.generate_report())
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ParamValidationError: Parameter validation failed:
    Invalid type for parameter InstanceIds, value: i-0844f33bdf9c15e5c, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
[31m[2022-06-17 21:23:44 ERROR] [activity:229][39m   => failed: botocore.exceptions.ParamValidationError: Parameter validation failed:
    Invalid type for parameter InstanceIds, value: i-0844f33bdf9c15e5c, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
[36m[2022-06-17 21:23:44 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 21:23:44 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 21:23:44 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 21:23:44 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 21:23:44 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 21:23:44 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 21:23:44 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 21:23:44 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 21:23:44 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 21:23:44 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:23:55 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:23:55 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:23:55 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:23:59 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:23:59 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:23:59 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:23:59 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:23:59 DEBUG] [caching:35][39m Cached 2 activities
[32m[2022-06-17 21:23:59 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 21:23:59 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:23:59 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:23:59 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 21:23:59 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 21:23:59 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:23:59 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:23:59 DEBUG] [caching:35][39m Cached 2 activities
[36m[2022-06-17 21:23:59 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 21:23:59 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 21:23:59 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 21:23:59 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 21:23:59 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 21:23:59 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 21:23:59 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 21:23:59 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 21:23:59 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 21:23:59 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 21:23:59 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 21:23:59 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 21:23:59 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 21:23:59 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 21:23:59 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 21:23:59 DEBUG] [__init__:75][39m Using AWS region 'us-east-1'
[36m[2022-06-17 21:23:59 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 21:23:59 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-0844f33bdf9c15e5c']})' from AZ 'None' to be stopped
[36m[2022-06-17 21:23:59 DEBUG] [actions:587][39m Stopping instances: ['i-0844f33bdf9c15e5c']
[36m[2022-06-17 21:24:00 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 80, 'Name': 'stopped'}, 'InstanceId': 'i-0844f33bdf9c15e5c', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}], 'ResponseMetadata': {'RequestId': 'c371a066-fdbe-4a1e-8580-2090e8ecc53a', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'c371a066-fdbe-4a1e-8580-2090e8ecc53a', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '578', 'date': 'Sat, 18 Jun 2022 01:24:05 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 21:24:00 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 21:24:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 21:24:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 21:24:10 INFO] [activity:204][39m Action: start-an-ec2-instance
[36m[2022-06-17 21:24:10 DEBUG] [python:33][39m Activity 'start-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 21:24:10 DEBUG] [__init__:75][39m Using AWS region 'us-east-1'
[36m[2022-06-17 21:24:10 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 21:24:10 DEBUG] [actions:645][39m Starting normal instance(s): ['i-0844f33bdf9c15e5c']
[36m[2022-06-17 21:24:10 DEBUG] [activity:221][39m   => succeeded with '[{'CurrentState': {'Code': 0, 'Name': 'pending'}, 'InstanceId': 'i-0844f33bdf9c15e5c', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}]'
[36m[2022-06-17 21:24:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 21:24:10 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 21:24:10 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 21:24:10 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 21:24:10 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 21:24:10 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 21:24:10 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 21:24:10 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 21:24:10 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 21:24:10 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:49:59 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:49:59 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:49:59 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:49:59 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:49:59 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:49:59 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:49:59 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:49:59 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:50:24 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:50:24 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:50:24 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:50:24 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:50:24 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:50:24 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:50:24 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:50:24 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:50:53 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:50:53 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:50:53 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:50:53 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:50:53 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:50:53 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:50:53 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:50:53 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:51:54 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:51:54 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:51:54 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:51:55 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:51:55 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:51:55 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:51:55 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:51:55 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:55:22 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:55:22 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:55:22 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:55:22 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:55:22 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:55:22 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:55:22 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:55:22 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:55:48 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:55:48 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:55:48 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:55:48 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:55:48 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:55:48 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:55:48 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:55:48 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:56:41 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:56:41 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:56:41 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:56:41 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:56:41 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:56:41 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:56:41 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:56:41 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 21:59:05 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 21:59:05 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 21:59:05 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 21:59:06 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 21:59:06 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:59:06 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 21:59:06 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 21:59:06 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:00:07 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:00:07 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:00:07 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:00:08 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:00:08 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:00:08 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:00:08 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:00:08 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:00:35 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:00:35 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:00:35 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:00:36 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:00:36 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:00:36 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:00:36 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:00:36 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-06-17 22:00:36 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:00:36 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:00:36 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:00:36 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 22:00:36 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 22:00:36 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:00:36 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:00:36 DEBUG] [caching:35][39m Cached 1 activities
[36m[2022-06-17 22:00:36 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:00:36 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:00:36 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:00:36 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 22:00:36 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 22:00:36 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 22:00:36 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 22:00:36 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 22:00:36 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 22:00:36 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 22:00:36 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 22:00:36 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 22:00:36 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:00:36 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 22:00:36 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:00:36 DEBUG] [__init__:75][39m Using AWS region 'us-east-1'
[36m[2022-06-17 22:00:36 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:00:36 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-0844f33bdf9c15e5c']})' from AZ 'None' to be stopped
[36m[2022-06-17 22:00:36 DEBUG] [actions:587][39m Stopping instances: ['i-0844f33bdf9c15e5c']
[36m[2022-06-17 22:00:37 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 72, in stop_instance
        return stop_instances_any_type(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 590, in stop_instances_any_type
        client.stop_instances(InstanceIds=instance_types["normal"], Force=force)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StopInstances operation: This instance 'i-0844f33bdf9c15e5c' is not in a state from which it can be stopped.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 72, in stop_instance
        return stop_instances_any_type(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 590, in stop_instances_any_type
        client.stop_instances(InstanceIds=instance_types["normal"], Force=force)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StopInstances operation: This instance 'i-0844f33bdf9c15e5c' is not in a state from which it can be stopped.
[31m[2022-06-17 22:00:37 ERROR] [activity:229][39m   => failed: botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StopInstances operation: This instance 'i-0844f33bdf9c15e5c' is not in a state from which it can be stopped.
[32m[2022-06-17 22:00:37 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:00:47 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:00:47 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 22:00:47 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 22:00:47 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:00:47 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 22:00:47 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:00:47 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 22:00:47 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 22:00:47 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 22:00:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:00:53 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:00:53 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:00:53 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:00:53 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:00:53 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:00:53 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:00:53 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:00:53 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-06-17 22:00:53 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:00:53 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:00:53 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:00:53 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 22:00:53 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 22:00:53 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:00:53 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:00:53 DEBUG] [caching:35][39m Cached 1 activities
[36m[2022-06-17 22:00:53 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:00:53 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:00:53 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:00:53 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 22:00:53 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 22:00:53 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 22:00:53 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 22:00:53 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 22:00:53 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 22:00:53 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 22:00:53 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 22:00:53 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 22:00:53 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:00:53 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 22:00:53 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:00:53 DEBUG] [__init__:75][39m Using AWS region 'us-east-1'
[36m[2022-06-17 22:00:53 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:00:54 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 68, in stop_instance
        instance_types = get_instance_type_by_id([instance_id], client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 573, in get_instance_type_by_id
        res = client.describe_instances(InstanceIds=instance_ids)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-03097a9f6e8dfa772' does not exist
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 68, in stop_instance
        instance_types = get_instance_type_by_id([instance_id], client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 573, in get_instance_type_by_id
        res = client.describe_instances(InstanceIds=instance_ids)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-03097a9f6e8dfa772' does not exist
[31m[2022-06-17 22:00:54 ERROR] [activity:229][39m   => failed: botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-03097a9f6e8dfa772' does not exist
[32m[2022-06-17 22:00:54 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:01:04 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:01:04 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 22:01:04 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 22:01:04 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:01:04 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 22:01:04 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:01:04 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 22:01:04 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 22:01:04 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 22:01:04 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:01:08 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:01:08 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:01:08 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:01:09 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:01:09 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:01:09 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:01:09 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:01:09 DEBUG] [caching:35][39m Cached 1 activities
[32m[2022-06-17 22:01:09 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:01:09 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:01:09 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:01:09 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 22:01:09 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 22:01:09 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:01:09 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:01:09 DEBUG] [caching:35][39m Cached 1 activities
[36m[2022-06-17 22:01:09 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:01:09 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:01:09 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:01:09 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 22:01:09 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 22:01:09 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 22:01:09 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 22:01:09 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 22:01:09 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 22:01:09 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 22:01:09 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 22:01:09 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 22:01:09 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:01:09 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 22:01:09 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:01:09 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:01:09 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:01:09 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 22:01:09 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 22:01:10 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '64f222db-013d-4b64-92e0-9f42dfc1b65d', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '64f222db-013d-4b64-92e0-9f42dfc1b65d', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 02:01:15 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 22:01:10 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:01:20 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:01:20 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 22:01:20 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 22:01:20 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:01:20 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 22:01:20 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:01:20 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 22:01:20 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 22:01:20 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 22:01:20 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:02:00 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:02:00 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:02:00 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:02:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:02:01 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:02:01 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:02:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:02:01 DEBUG] [caching:35][39m Cached 2 activities
[32m[2022-06-17 22:02:01 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:02:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:02:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:02:01 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:02:01 DEBUG] [caching:42][39m Clearing activities cache
[31m[2022-06-17 22:02:01 ERROR] [cli:260][39m argument 'instance_id' is not part of the function signature in activity 'detach_random_volume'
[36m[2022-06-17 22:02:01 DEBUG] [cli:261][39m argument 'instance_id' is not part of the function signature in activity 'detach_random_volume'
[36m[2022-06-17 22:02:19 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:02:19 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:02:19 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:02:20 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:02:20 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:02:20 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:02:20 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:02:20 DEBUG] [caching:35][39m Cached 2 activities
[32m[2022-06-17 22:02:20 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:02:20 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:02:20 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:02:20 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 22:02:20 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 22:02:20 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:02:20 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:02:20 DEBUG] [caching:35][39m Cached 2 activities
[36m[2022-06-17 22:02:20 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:02:20 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:02:20 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:02:20 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 22:02:20 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 22:02:20 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 22:02:20 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 22:02:20 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 22:02:20 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 22:02:20 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 22:02:20 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 22:02:20 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 22:02:20 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:02:20 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 22:02:20 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:02:20 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:02:20 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:02:20 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 22:02:20 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 22:02:20 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 80, 'Name': 'stopped'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}], 'ResponseMetadata': {'RequestId': '28371de3-f14e-4d6c-9bd7-9deb19982701', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '28371de3-f14e-4d6c-9bd7-9deb19982701', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '578', 'date': 'Sat, 18 Jun 2022 02:02:25 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 22:02:20 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:02:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:02:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:02:30 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 22:02:30 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:02:30 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:02:30 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:02:31 DEBUG] [activity:221][39m   => succeeded with '[{'AttachTime': datetime.datetime(2022, 6, 18, 1, 55, 19, tzinfo=tzutc()), 'Device': '/dev/sdf', 'InstanceId': 'i-03097a9f6e8dfa772', 'State': 'detaching', 'VolumeId': 'vol-06a0d4f85a8ec9340', 'ResponseMetadata': {'RequestId': '1ac0edc7-057b-4bcd-9b16-4ea564cea489', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '1ac0edc7-057b-4bcd-9b16-4ea564cea489', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '410', 'date': 'Sat, 18 Jun 2022 02:02:36 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[36m[2022-06-17 22:02:31 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:02:31 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 22:02:31 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 22:02:31 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:02:31 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 22:02:31 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:02:31 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 22:02:31 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 22:02:31 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 22:02:31 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:03:51 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:03:51 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:03:51 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:03:51 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:03:51 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:03:51 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:03:51 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:03:51 DEBUG] [caching:35][39m Cached 3 activities
[32m[2022-06-17 22:03:51 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:03:51 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:03:51 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:03:51 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:03:51 DEBUG] [caching:42][39m Clearing activities cache
[31m[2022-06-17 22:03:51 ERROR] [cli:260][39m argument 'instance_id' is not part of the function signature in activity 'start_instances'
[36m[2022-06-17 22:03:51 DEBUG] [cli:261][39m argument 'instance_id' is not part of the function signature in activity 'start_instances'
[36m[2022-06-17 22:05:16 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:05:16 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:05:16 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:05:17 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:05:17 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:05:17 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:05:17 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:05:17 DEBUG] [caching:35][39m Cached 3 activities
[32m[2022-06-17 22:05:17 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:05:17 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:05:17 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:05:17 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 22:05:17 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 22:05:17 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:05:17 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:05:17 DEBUG] [caching:35][39m Cached 3 activities
[36m[2022-06-17 22:05:17 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:05:17 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:05:17 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:05:17 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 22:05:17 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 22:05:17 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 22:05:17 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 22:05:17 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 22:05:17 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 22:05:17 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 22:05:17 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 22:05:17 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 22:05:17 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:05:17 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 22:05:17 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:05:17 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:05:17 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:05:17 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 22:05:17 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 22:05:17 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '2da46dd7-d004-4086-870f-ea24baa74978', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '2da46dd7-d004-4086-870f-ea24baa74978', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 02:05:23 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 22:05:17 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:05:27 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:05:27 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:05:27 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 22:05:27 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:05:27 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:05:27 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:05:28 DEBUG] [activity:221][39m   => succeeded with '[]'
[32m[2022-06-17 22:05:28 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:05:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:05:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:05:38 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 22:05:38 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:05:38 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:05:38 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:05:38 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 284, in start_instances
        instance_types = get_instance_type_by_id(instance_ids, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 573, in get_instance_type_by_id
        res = client.describe_instances(InstanceIds=instance_ids)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 874, in _make_api_call
        request_dict = self._convert_to_request_dict(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 935, in _convert_to_request_dict
        request_dict = self._serializer.serialize_to_request(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/validate.py", line 381, in serialize_to_request
        raise ParamValidationError(report=report.generate_report())
    botocore.exceptions.ParamValidationError: Parameter validation failed:
    Invalid type for parameter InstanceIds, value: i-03097a9f6e8dfa772, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 284, in start_instances
        instance_types = get_instance_type_by_id(instance_ids, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 573, in get_instance_type_by_id
        res = client.describe_instances(InstanceIds=instance_ids)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 874, in _make_api_call
        request_dict = self._convert_to_request_dict(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 935, in _convert_to_request_dict
        request_dict = self._serializer.serialize_to_request(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/validate.py", line 381, in serialize_to_request
        raise ParamValidationError(report=report.generate_report())
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ParamValidationError: Parameter validation failed:
    Invalid type for parameter InstanceIds, value: i-03097a9f6e8dfa772, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
[31m[2022-06-17 22:05:38 ERROR] [activity:229][39m   => failed: botocore.exceptions.ParamValidationError: Parameter validation failed:
    Invalid type for parameter InstanceIds, value: i-03097a9f6e8dfa772, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
[36m[2022-06-17 22:05:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:05:38 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 22:05:38 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 22:05:38 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:05:38 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 22:05:38 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:05:38 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 22:05:38 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 22:05:38 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 22:05:38 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:06:24 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 22:06:24 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 22:06:24 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 22:06:24 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 22:06:24 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:06:24 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 22:06:24 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:06:24 DEBUG] [caching:35][39m Cached 3 activities
[32m[2022-06-17 22:06:24 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 22:06:24 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:06:24 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:06:24 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 22:06:25 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 22:06:25 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 22:06:25 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 22:06:25 DEBUG] [caching:35][39m Cached 3 activities
[36m[2022-06-17 22:06:25 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 22:06:25 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 22:06:25 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 22:06:25 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 22:06:25 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 22:06:25 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 22:06:25 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 22:06:25 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 22:06:25 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 22:06:25 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 22:06:25 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 22:06:25 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 22:06:25 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:06:25 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 22:06:25 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:06:25 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:06:25 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:06:25 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 22:06:25 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 22:06:25 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '687839e6-b4b8-44da-8802-a17f50b9e9f2', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '687839e6-b4b8-44da-8802-a17f50b9e9f2', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 02:06:30 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 22:06:25 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:06:35 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:06:35 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:06:35 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 22:06:35 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:06:35 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:06:35 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:06:36 DEBUG] [activity:221][39m   => succeeded with '[]'
[32m[2022-06-17 22:06:36 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 22:06:46 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:06:46 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 22:06:46 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 22:06:46 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 22:06:46 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 22:06:46 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 22:06:46 DEBUG] [actions:645][39m Starting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 22:06:47 DEBUG] [activity:221][39m   => succeeded with '[{'CurrentState': {'Code': 0, 'Name': 'pending'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}]'
[36m[2022-06-17 22:06:47 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 22:06:47 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 22:06:47 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 22:06:47 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:06:47 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 22:06:47 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 22:06:47 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 22:06:47 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 22:06:47 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 22:06:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:05:42 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:05:42 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:05:42 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:05:42 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:05:42 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:05:42 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:05:42 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:05:42 DEBUG] [caching:35][39m Cached 3 activities
[32m[2022-06-17 23:05:42 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:05:42 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:05:42 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:05:42 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 23:05:42 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 23:05:42 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:05:42 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:05:42 DEBUG] [caching:35][39m Cached 3 activities
[36m[2022-06-17 23:05:42 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:05:42 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:05:42 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:05:42 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 23:05:42 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 23:05:42 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 23:05:42 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 23:05:42 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 23:05:42 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 23:05:42 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 23:05:42 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 23:05:42 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 23:05:42 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:05:42 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 23:05:42 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:05:42 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:05:42 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:05:43 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 23:05:43 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:05:43 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '929679a4-62f6-451f-a7b3-c1934819d178', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '929679a4-62f6-451f-a7b3-c1934819d178', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 03:05:48 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:05:43 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:05:53 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:05:53 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:05:53 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 23:05:53 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:05:53 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:05:53 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:05:54 DEBUG] [activity:221][39m   => succeeded with '[{'AttachTime': datetime.datetime(2022, 6, 18, 2, 8, 26, tzinfo=tzutc()), 'Device': '/dev/sdf', 'InstanceId': 'i-03097a9f6e8dfa772', 'State': 'detaching', 'VolumeId': 'vol-06a0d4f85a8ec9340', 'ResponseMetadata': {'RequestId': 'f2986ea8-2603-4724-85b1-ab0a504f5416', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'f2986ea8-2603-4724-85b1-ab0a504f5416', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '410', 'date': 'Sat, 18 Jun 2022 03:05:58 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:05:54 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:06:04 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:06:04 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:06:04 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 23:06:04 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:06:04 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:06:04 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:06:04 DEBUG] [actions:645][39m Starting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:06:05 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 285, in start_instances
        return start_instances_any_type(instance_types, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 646, in start_instances_any_type
        response = client.start_instances(InstanceIds=v)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-03097a9f6e8dfa772' is not in a state from which it can be started.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 285, in start_instances
        return start_instances_any_type(instance_types, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 646, in start_instances_any_type
        response = client.start_instances(InstanceIds=v)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-03097a9f6e8dfa772' is not in a state from which it can be started.
[31m[2022-06-17 23:06:05 ERROR] [activity:229][39m   => failed: botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-03097a9f6e8dfa772' is not in a state from which it can be started.
[36m[2022-06-17 23:06:05 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:06:05 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 23:06:05 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 23:06:05 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:06:05 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 23:06:05 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:06:05 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 23:06:05 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 23:06:05 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 23:06:05 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:10:00 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:10:00 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:10:00 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:10:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:10:01 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:10:01 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:10:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:10:01 DEBUG] [caching:35][39m Cached 3 activities
[32m[2022-06-17 23:10:01 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:10:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:10:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:10:01 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:10:01 DEBUG] [caching:42][39m Clearing activities cache
[31m[2022-06-17 23:10:01 ERROR] [cli:260][39m The python module 'chaosaws.ec2.actions' does not expose a function called 'restart-instances' in action 'restart-instances'
[36m[2022-06-17 23:10:01 DEBUG] [cli:261][39m The python module 'chaosaws.ec2.actions' does not expose a function called 'restart-instances' in action 'restart-instances'
[36m[2022-06-17 23:10:34 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:10:34 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:10:34 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:10:34 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:10:34 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:10:34 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:10:34 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:10:34 DEBUG] [caching:35][39m Cached 3 activities
[32m[2022-06-17 23:10:34 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:10:34 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:10:34 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:10:34 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 23:10:34 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 23:10:34 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:10:34 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:10:34 DEBUG] [caching:35][39m Cached 3 activities
[36m[2022-06-17 23:10:34 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:10:34 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:10:34 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:10:34 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 23:10:34 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 23:10:34 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 23:10:34 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 23:10:34 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 23:10:34 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 23:10:34 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 23:10:34 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 23:10:34 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 23:10:34 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:10:34 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 23:10:34 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:10:34 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:10:34 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:10:35 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 23:10:35 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:10:35 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '7f879e50-8f88-45e0-8613-0ca10151c7fc', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '7f879e50-8f88-45e0-8613-0ca10151c7fc', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 03:10:41 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:10:35 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:10:45 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:10:45 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:10:45 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 23:10:45 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:10:45 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:10:45 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:10:45 DEBUG] [activity:221][39m   => succeeded with '[]'
[32m[2022-06-17 23:10:45 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:10:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:10:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:10:55 INFO] [activity:204][39m Action: restart-instances
[36m[2022-06-17 23:10:55 DEBUG] [python:33][39m Activity 'restart-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:10:55 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:10:55 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:10:56 DEBUG] [actions:657][39m Restarting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:10:56 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 337, in restart_instances
        return restart_instances_any_type(instance_types, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 658, in restart_instances_any_type
        client.reboot_instances(InstanceIds=v)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (IncorrectState) when calling the RebootInstances operation: Cannot reboot instance i-03097a9f6e8dfa772 that is currently in stopped state.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 337, in restart_instances
        return restart_instances_any_type(instance_types, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 658, in restart_instances_any_type
        client.reboot_instances(InstanceIds=v)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ClientError: An error occurred (IncorrectState) when calling the RebootInstances operation: Cannot reboot instance i-03097a9f6e8dfa772 that is currently in stopped state.
[31m[2022-06-17 23:10:56 ERROR] [activity:229][39m   => failed: botocore.exceptions.ClientError: An error occurred (IncorrectState) when calling the RebootInstances operation: Cannot reboot instance i-03097a9f6e8dfa772 that is currently in stopped state.
[36m[2022-06-17 23:10:56 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:10:56 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 23:10:56 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 23:10:56 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:10:56 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 23:10:56 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:10:56 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 23:10:56 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 23:10:56 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 23:10:56 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:12:00 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:12:00 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:12:00 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:12:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:12:01 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:12:01 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:12:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:12:01 DEBUG] [caching:35][39m Cached 3 activities
[32m[2022-06-17 23:12:01 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:12:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:12:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:12:01 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 23:12:01 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 23:12:01 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:12:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:12:01 DEBUG] [caching:35][39m Cached 3 activities
[36m[2022-06-17 23:12:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:12:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:12:01 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:12:01 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 23:12:01 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 23:12:01 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 23:12:01 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 23:12:01 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 23:12:01 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 23:12:01 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 23:12:01 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 23:12:01 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 23:12:01 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:12:01 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 23:12:01 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:12:01 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:12:01 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:12:01 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 23:12:01 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:12:01 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 80, 'Name': 'stopped'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}], 'ResponseMetadata': {'RequestId': 'a0a11598-9ad4-49a3-93e9-a8bc4bb6f913', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'a0a11598-9ad4-49a3-93e9-a8bc4bb6f913', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '578', 'date': 'Sat, 18 Jun 2022 03:12:07 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:12:01 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:12:11 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:12:11 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:12:11 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 23:12:11 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:12:11 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:12:11 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:12:12 DEBUG] [activity:221][39m   => succeeded with '[]'
[32m[2022-06-17 23:12:12 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:12:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:12:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:12:22 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 23:12:22 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:12:22 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:12:22 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:12:22 DEBUG] [actions:645][39m Starting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:12:23 DEBUG] [activity:221][39m   => succeeded with '[{'CurrentState': {'Code': 0, 'Name': 'pending'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}]'
[36m[2022-06-17 23:12:23 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:12:23 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 23:12:23 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 23:12:23 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:12:23 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 23:12:23 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:12:23 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 23:12:23 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 23:12:23 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 23:12:23 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:18:04 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:18:04 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:18:04 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:18:05 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:18:05 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:18:05 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:18:05 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:18:05 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-06-17 23:18:05 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:18:05 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:18:05 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:18:05 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 23:18:05 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 23:18:05 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:18:05 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:18:05 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-06-17 23:18:05 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:18:05 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:18:05 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:18:05 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 23:18:05 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 23:18:05 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 23:18:05 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 23:18:05 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 23:18:05 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 23:18:05 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 23:18:05 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 23:18:05 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 23:18:05 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:18:05 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 23:18:05 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:18:05 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:18:05 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:18:05 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 23:18:05 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:18:06 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': 'ca70ea75-cde3-44c2-a73d-2c7703e9889c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'ca70ea75-cde3-44c2-a73d-2c7703e9889c', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 03:18:11 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:18:06 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:18:16 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:18:16 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:18:16 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 23:18:16 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:18:16 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:18:16 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:18:16 DEBUG] [activity:221][39m   => succeeded with '[]'
[32m[2022-06-17 23:18:16 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:18:26 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:18:26 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:18:26 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 23:18:26 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:18:26 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:18:26 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:18:26 DEBUG] [actions:645][39m Starting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:18:27 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 285, in start_instances
        return start_instances_any_type(instance_types, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 646, in start_instances_any_type
        response = client.start_instances(InstanceIds=v)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-03097a9f6e8dfa772' is not in a state from which it can be started.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 285, in start_instances
        return start_instances_any_type(instance_types, client)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 646, in start_instances_any_type
        response = client.start_instances(InstanceIds=v)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    chaoslib.exceptions.ActivityFailed: botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-03097a9f6e8dfa772' is not in a state from which it can be started.
[31m[2022-06-17 23:18:27 ERROR] [activity:229][39m   => failed: botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-03097a9f6e8dfa772' is not in a state from which it can be started.
[32m[2022-06-17 23:18:27 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:18:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:18:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:18:37 INFO] [activity:204][39m Action: attach-volume
[36m[2022-06-17 23:18:37 DEBUG] [python:33][39m Activity 'attach-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:18:37 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:18:37 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:18:38 DEBUG] [actions:713][39m Attached volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772
[36m[2022-06-17 23:18:38 DEBUG] [activity:221][39m   => succeeded with '[{'AttachTime': datetime.datetime(2022, 6, 18, 3, 18, 43, 843000, tzinfo=tzutc()), 'Device': '/dev/sdf', 'InstanceId': 'i-03097a9f6e8dfa772', 'State': 'attaching', 'VolumeId': 'vol-06a0d4f85a8ec9340', 'ResponseMetadata': {'RequestId': '673fa409-eb35-41a8-997d-c4489447c385', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '673fa409-eb35-41a8-997d-c4489447c385', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '410', 'date': 'Sat, 18 Jun 2022 03:18:43 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[36m[2022-06-17 23:18:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:18:38 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 23:18:38 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 23:18:38 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:18:38 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 23:18:38 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:18:38 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 23:18:38 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 23:18:38 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 23:18:38 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:20:36 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:20:36 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:20:36 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:20:37 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:20:37 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:20:37 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:20:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:20:37 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-06-17 23:20:37 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:20:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:20:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:20:37 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 23:20:37 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 23:20:37 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:20:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:20:37 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-06-17 23:20:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:20:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:20:37 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:20:37 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 23:20:37 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 23:20:37 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 23:20:37 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 23:20:37 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 23:20:37 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 23:20:37 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 23:20:37 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 23:20:37 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 23:20:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:20:37 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 23:20:37 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:20:37 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:20:37 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:20:37 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 23:20:37 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:20:38 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 80, 'Name': 'stopped'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}], 'ResponseMetadata': {'RequestId': '6a24d53e-4eaf-45de-875e-b5cb07c46ea1', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '6a24d53e-4eaf-45de-875e-b5cb07c46ea1', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '578', 'date': 'Sat, 18 Jun 2022 03:20:42 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:20:38 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:20:48 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:20:48 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:20:48 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 23:20:48 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:20:48 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:20:48 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:20:48 DEBUG] [activity:221][39m   => succeeded with '[{'AttachTime': datetime.datetime(2022, 6, 18, 3, 18, 43, tzinfo=tzutc()), 'Device': '/dev/sdf', 'InstanceId': 'i-03097a9f6e8dfa772', 'State': 'detaching', 'VolumeId': 'vol-06a0d4f85a8ec9340', 'ResponseMetadata': {'RequestId': 'f9b039b5-a2e3-4be5-bba7-c99ab0c7c963', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'f9b039b5-a2e3-4be5-bba7-c99ab0c7c963', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '410', 'date': 'Sat, 18 Jun 2022 03:20:53 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:20:48 INFO] [activity:239][39m Pausing after activity for 15s...
[36m[2022-06-17 23:21:03 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:21:03 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:21:03 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 23:21:03 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:21:03 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:21:03 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:21:04 DEBUG] [actions:645][39m Starting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:21:04 DEBUG] [activity:221][39m   => succeeded with '[{'CurrentState': {'Code': 0, 'Name': 'pending'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}]'
[32m[2022-06-17 23:21:04 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:21:14 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:21:14 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:21:14 INFO] [activity:204][39m Action: attach-volume
[36m[2022-06-17 23:21:14 DEBUG] [python:33][39m Activity 'attach-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:21:14 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:21:14 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:21:15 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 710, in attach_instance_volume
        response = client.attach_volume(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (IncorrectState) when calling the AttachVolume operation: Instance 'i-03097a9f6e8dfa772' is not 'running'.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 419, in attach_volume
        attach_instance_volume(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 715, in attach_instance_volume
        raise FailedActivity(
    chaoslib.exceptions.ActivityFailed: Unable to attach volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772: Instance 'i-03097a9f6e8dfa772' is not 'running'.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 419, in attach_volume
        attach_instance_volume(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 715, in attach_instance_volume
        raise FailedActivity(
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: Unable to attach volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772: Instance 'i-03097a9f6e8dfa772' is not 'running'.
[31m[2022-06-17 23:21:15 ERROR] [activity:229][39m   => failed: chaoslib.exceptions.ActivityFailed: Unable to attach volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772: Instance 'i-03097a9f6e8dfa772' is not 'running'.
[32m[2022-06-17 23:21:15 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:21:25 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:21:25 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 23:21:25 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 23:21:25 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:21:25 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 23:21:25 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:21:25 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 23:21:25 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 23:21:25 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 23:21:25 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:21:35 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:21:35 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:21:35 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:21:35 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:21:35 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:21:35 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:21:35 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:21:35 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-06-17 23:21:35 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:21:35 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:21:35 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:21:35 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 23:21:35 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 23:21:35 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:21:35 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:21:35 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-06-17 23:21:35 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:21:35 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:21:35 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:21:35 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 23:21:35 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 23:21:35 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 23:21:35 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 23:21:35 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 23:21:35 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 23:21:35 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 23:21:35 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 23:21:35 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 23:21:35 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:21:35 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 23:21:35 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:21:35 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:21:35 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:21:36 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 23:21:36 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:21:36 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '8fd9fd1a-1b11-4fdf-b572-3a77515730d6', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '8fd9fd1a-1b11-4fdf-b572-3a77515730d6', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 03:21:41 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:21:36 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:21:46 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:21:46 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:21:46 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 23:21:46 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:21:46 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:21:46 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:21:47 DEBUG] [activity:221][39m   => succeeded with '[]'
[32m[2022-06-17 23:21:47 INFO] [activity:239][39m Pausing after activity for 15s...
[36m[2022-06-17 23:22:02 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:22:02 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:22:02 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 23:22:02 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:22:02 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:22:02 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:22:02 DEBUG] [actions:645][39m Starting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:22:02 DEBUG] [activity:221][39m   => succeeded with '[{'CurrentState': {'Code': 0, 'Name': 'pending'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}]'
[32m[2022-06-17 23:22:02 INFO] [activity:239][39m Pausing after activity for 20s...
[36m[2022-06-17 23:22:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:22:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:22:22 INFO] [activity:204][39m Action: attach-volume
[36m[2022-06-17 23:22:22 DEBUG] [python:33][39m Activity 'attach-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:22:22 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:22:22 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:22:23 DEBUG] [activity:276][39m Activity failed
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 710, in attach_instance_volume
        response = client.attach_volume(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.exceptions.ClientError: An error occurred (IncorrectState) when calling the AttachVolume operation: Instance 'i-03097a9f6e8dfa772' is not 'running'.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 419, in attach_volume
        attach_instance_volume(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 715, in attach_instance_volume
        raise FailedActivity(
    chaoslib.exceptions.ActivityFailed: Unable to attach volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772: Instance 'i-03097a9f6e8dfa772' is not 'running'.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 269, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 419, in attach_volume
        attach_instance_volume(
      File "/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py", line 715, in attach_instance_volume
        raise FailedActivity(
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: Unable to attach volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772: Instance 'i-03097a9f6e8dfa772' is not 'running'.
[31m[2022-06-17 23:22:23 ERROR] [activity:229][39m   => failed: chaoslib.exceptions.ActivityFailed: Unable to attach volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772: Instance 'i-03097a9f6e8dfa772' is not 'running'.
[32m[2022-06-17 23:22:23 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:22:33 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:22:33 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 23:22:33 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 23:22:33 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:22:33 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 23:22:33 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:22:33 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 23:22:33 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 23:22:33 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 23:22:33 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:22:40 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-17 23:22:40 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-17 23:22:40 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-17 23:22:40 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-17 23:22:40 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:22:40 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-17 23:22:40 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:22:40 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-06-17 23:22:40 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-17 23:22:40 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:22:40 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:22:40 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-17 23:22:40 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-17 23:22:40 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-17 23:22:40 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-17 23:22:40 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-06-17 23:22:40 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-17 23:22:40 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-17 23:22:40 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-17 23:22:40 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-17 23:22:40 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-17 23:22:40 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-17 23:22:40 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-17 23:22:40 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-17 23:22:40 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-17 23:22:40 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-17 23:22:40 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-17 23:22:40 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-17 23:22:40 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:22:40 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-17 23:22:40 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:22:40 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:22:40 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:22:41 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-03097a9f6e8dfa772']})' from AZ 'None' to be stopped
[36m[2022-06-17 23:22:41 DEBUG] [actions:587][39m Stopping instances: ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:22:41 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': 'b0e2ac38-e592-43f2-b370-81fd746a4d81', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'b0e2ac38-e592-43f2-b370-81fd746a4d81', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 03:22:46 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:22:41 INFO] [activity:239][39m Pausing after activity for 20s...
[36m[2022-06-17 23:23:01 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:23:01 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:23:01 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-17 23:23:01 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:23:01 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:23:01 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:23:01 DEBUG] [activity:221][39m   => succeeded with '[]'
[32m[2022-06-17 23:23:01 INFO] [activity:239][39m Pausing after activity for 20s...
[36m[2022-06-17 23:23:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:23:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:23:22 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-17 23:23:22 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:23:22 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:23:22 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:23:22 DEBUG] [actions:645][39m Starting normal instance(s): ['i-03097a9f6e8dfa772']
[36m[2022-06-17 23:23:22 DEBUG] [activity:221][39m   => succeeded with '[{'CurrentState': {'Code': 0, 'Name': 'pending'}, 'InstanceId': 'i-03097a9f6e8dfa772', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}]'
[32m[2022-06-17 23:23:22 INFO] [activity:239][39m Pausing after activity for 30s...
[36m[2022-06-17 23:23:52 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:23:52 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-17 23:23:52 INFO] [activity:204][39m Action: attach-volume
[36m[2022-06-17 23:23:52 DEBUG] [python:33][39m Activity 'attach-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-17 23:23:52 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-17 23:23:52 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-17 23:23:54 DEBUG] [actions:713][39m Attached volume vol-06a0d4f85a8ec9340 to instance i-03097a9f6e8dfa772
[36m[2022-06-17 23:23:54 DEBUG] [activity:221][39m   => succeeded with '[{'AttachTime': datetime.datetime(2022, 6, 18, 3, 23, 59, 717000, tzinfo=tzutc()), 'Device': '/dev/sdf', 'InstanceId': 'i-03097a9f6e8dfa772', 'State': 'attaching', 'VolumeId': 'vol-06a0d4f85a8ec9340', 'ResponseMetadata': {'RequestId': '591821f9-d536-46be-9940-e9cae005ddc0', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '591821f9-d536-46be-9940-e9cae005ddc0', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '410', 'date': 'Sat, 18 Jun 2022 03:23:59 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-17 23:23:54 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-17 23:24:04 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-17 23:24:04 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-17 23:24:04 INFO] [run:893][39m Let's rollback...
[36m[2022-06-17 23:24:04 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:24:04 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-17 23:24:04 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-17 23:24:04 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-17 23:24:04 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-17 23:24:04 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-17 23:24:04 DEBUG] [caching:42][39m Clearing activities cache
